### ISSUE TITLE
  TypeError: ObjectId('') is not JSON serializable when identity_changed

### ISSUE THREAD

**Issue by chusov** [mattupstate/flask-security#148]
with MongoEngine when identity_changed.send(app,identity=Identity(user.id))

User class is using the default mongoengine id field, which is the same as http://pythonhosted.org/Flask-Security/quickstart.html 

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in **call**
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/usr/local/lib/python2.7/dist-packages/flask/sessions.py", line 326, in save_session
    val = self.get_signing_serializer(app).dumps(dict(session))
  File "/usr/local/lib/python2.7/dist-packages/itsdangerous.py", line 537, in dumps
    payload = want_bytes(self.dump_payload(obj))
  File "/usr/local/lib/python2.7/dist-packages/itsdangerous.py", line 809, in dump_payload
    json = super(URLSafeSerializerMixin, self).dump_payload(obj)
  File "/usr/local/lib/python2.7/dist-packages/itsdangerous.py", line 522, in dump_payload
    return want_bytes(self.serializer.dumps(obj))
  File "/usr/local/lib/python2.7/dist-packages/flask/sessions.py", line 85, in dumps
    return json.dumps(_tag(value), separators=(',', ':'))
  File "/usr/local/lib/python2.7/dist-packages/flask/json.py", line 126, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 202, in encode
    chunks = list(chunks)
  File "/usr/lib/python2.7/json/encoder.py", line 427, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 401, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 435, in _iterencode
    o = _default(o)
  File "/usr/local/lib/python2.7/dist-packages/flask/json.py", line 83, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/lib/python2.7/json/encoder.py", line 177, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: ObjectId('5204c0b32ef2cb7cedee9a08') is not JSON serializable

My login class:

@app.route('/login/', methods=['GET', 'POST'])
def login_view():
    form = LoginForm()

```
if form.validate_on_submit():
    user = user_datastore.find_user(email=form.email.data)


    try:
            if form.password.data == user.password:
                login_user(user)

                identity_changed.send(app,identity=Identity(user.id))

                flash('Yep!!!!!!!', 'error')
                return redirect(url_for('admin.index'))
            else:
                flash('Wrong email or password', 'alerts-error')
    except:
            flash('Wrong email or password', 'alerts-error')
return render_template('form_login.html', form=form)
```

I I change 
                    identity_changed.send(app,identity=Identity(user.id))
to 
                    identity_changed.send(app,identity=Identity(str(user.id)))
all fine.

I'm doing it wrong or error in the flask-security

**Comment by darker0n** [comment]
Thank you very much :+1:
