### ISSUE TITLE
DetachedInstanceError on Register

### ISSUE THREAD

**Issue by monkeysecurity** [mattupstate/flask-security#336]
After a user submits the register form, I'm getting an exception: 

```DetachedInstanceError: Parent instance <User at 0x4afc850> is not bound to a Session; lazy load operation of attribute 'roles' cannot proceed```

I have no idea what could be causing this.  Ideas?

    172.16.0.1 - - [09/Nov/2014 23:59:38] "POST /register HTTP/1.1" 500 -
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1836, in __call__
        return self.wsgi_app(environ, start_response)
      File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1820, in wsgi_app
        response = self.make_response(self.handle_exception(e))
      File "/usr/local/lib/python2.7/dist-packages/Flask_RESTful-0.2.5-py2.7.egg/flask_restful/__init__.py", line 145, in error_router
        return original_handler(e)
      File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1403, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
        response = self.full_dispatch_request()
      File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/usr/local/lib/python2.7/dist-packages/Flask_RESTful-0.2.5-py2.7.egg/flask_restful/__init__.py", line 145, in error_router
        return original_handler(e)
      File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
        rv = self.dispatch_request()
      File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/usr/local/lib/python2.7/dist-packages/Flask_Security-1.7.3-py2.7.egg/flask_security/decorators.py", line 205, in wrapper
        return f(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/Flask_Security-1.7.3-py2.7.egg/flask_security/views.py", line 122, in register
        login_user(user)
      File "/usr/local/lib/python2.7/dist-packages/Flask_Security-1.7.3-py2.7.egg/flask_security/utils.py", line 82, in login_user
        identity=Identity(user.id))
      File "/usr/local/lib/python2.7/dist-packages/blinker-1.3-py2.7.egg/blinker/base.py", line 267, in send
        for receiver in self.receivers_for(sender)]
      File "/usr/local/lib/python2.7/dist-packages/Flask_Principal-0.4.0-py2.7.egg/flask_principal.py", line 469, in _on_identity_changed
        self.set_identity(identity)
      File "/usr/local/lib/python2.7/dist-packages/Flask_Principal-0.4.0-py2.7.egg/flask_principal.py", line 418, in set_identity
        self._set_thread_identity(identity)
      File "/usr/local/lib/python2.7/dist-packages/Flask_Principal-0.4.0-py2.7.egg/flask_principal.py", line 463, in _set_thread_identity
        identity=identity)
      File "/usr/local/lib/python2.7/dist-packages/blinker-1.3-py2.7.egg/blinker/base.py", line 267, in send
        for receiver in self.receivers_for(sender)]
      File "/usr/local/lib/python2.7/dist-packages/Flask_Security-1.7.3-py2.7.egg/flask_security/core.py", line 214, in _on_identity_loaded
        for role in current_user.roles:
      File "/usr/local/lib/python2.7/dist-packages/Werkzeug-0.9.4-py2.7.egg/werkzeug/local.py", line 338, in __getattr__
        return getattr(self._get_current_object(), name)
      File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-0.9.2-py2.7-linux-x86_64.egg/sqlalchemy/orm/attributes.py", line 233, in __get__
        return self.impl.get(instance_state(instance), dict_)
      File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-0.9.2-py2.7-linux-x86_64.egg/sqlalchemy/orm/attributes.py", line 579, in get
        value = self.callable_(state, passive)
      File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-0.9.2-py2.7-linux-x86_64.egg/sqlalchemy/orm/strategies.py", line 478, in _load_for_state
        (orm_util.state_str(state), self.key)
    DetachedInstanceError: Parent instance <User at 0x4afc850> is not bound to a Session; lazy load operation of attribute 'roles' cannot proceed

**Comment by jonafato** [comment]
@monkeysecurity this can happen when you have a SQLAlchemy ORM model that has no session. Lazy loaded relationships (those that query the database upon first access to populate the attribute) require a session through which to query the database, so this error is thrown when one is not present.

I suspect the underlying cause of this error is related to your SQLAlchemy configuration tied to your application's user_datastore rather than Flask-Security itself. Can you provide more details about your application so we can find the source of this error?

**Comment by jonafato** [comment]
@monkeysecurity Without an example demonstrating this bug, I'm unable to confirm that this an issue within Flask-Security itself. If you're able to reproduce this, I'd like to help. If not, I'm inclined to think that this is not a bug in Flask-Security.

**Comment by jonafato** [comment]
@monkeysecurity I'm going to close this for now. If you can reproduce this, I'm happy to reopen it and help get the issue fixed.
