### ISSUE TITLE
AttributeError in decorator._check_token when POST a json list

### ISSUE THREAD

**Issue by houjunchen** [mattupstate/flask-security#428]
I have a POST API that receive a json array. When I decorated this method with `auth_token_required`, I received an `AttributeError`:

```
Traceback (most recent call last):
  File "/Users/abnerchen/.virtualenvs/coeus-dev/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/abnerchen/.virtualenvs/coeus-dev/lib/python3.4/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/abnerchen/.virtualenvs/coeus-dev/lib/python3.4/site-packages/flask_restful/__init__.py", line 270, in error_router
    return original_handler(e)
  File "/Users/abnerchen/.virtualenvs/coeus-dev/lib/python3.4/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/abnerchen/.virtualenvs/coeus-dev/lib/python3.4/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Users/abnerchen/.virtualenvs/coeus-dev/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/abnerchen/.virtualenvs/coeus-dev/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/abnerchen/.virtualenvs/coeus-dev/lib/python3.4/site-packages/flask_restful/__init__.py", line 270, in error_router
    return original_handler(e)
  File "/Users/abnerchen/.virtualenvs/coeus-dev/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/abnerchen/.virtualenvs/coeus-dev/lib/python3.4/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/Users/abnerchen/.virtualenvs/coeus-dev/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/abnerchen/.virtualenvs/coeus-dev/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/abnerchen/.virtualenvs/coeus-dev/lib/python3.4/site-packages/flask_restful/__init__.py", line 471, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/abnerchen/.virtualenvs/coeus-dev/lib/python3.4/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/abnerchen/.virtualenvs/coeus-dev/lib/python3.4/site-packages/flask_restful/__init__.py", line 581, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/abnerchen/.virtualenvs/coeus-dev/lib/python3.4/site-packages/flask_security/decorators.py", line 115, in decorated
    if _check_token():
  File "/Users/abnerchen/.virtualenvs/coeus-dev/lib/python3.4/site-packages/flask_security/decorators.py", line 57, in _check_token
    token = request.json.get(args_key, token)
AttributeError: 'list' object has no attribute 'get'
```

The is caused by `_check_token`:
```
def _check_token():
    header_key = _security.token_authentication_header
    args_key = _security.token_authentication_key
    header_token = request.headers.get(header_key, None)
    token = request.args.get(args_key, header_token)
    if request.get_json(silent=True):
        token = request.json.get(args_key, token)
    ...
```
where `request.json` will be a `list` not a `dict` when posting json array.

Is this an issue or my usage is wrong?

Here is part of my `requirements.txt`:
```
first==2.0.1
flask-login==0.2.11
flask-restful==0.3.4
flask-security==1.7.4
```

**Comment by houjunchen** [comment]
I think it way my wrong usage of POSTing json array without a key. So I close this issue.

**Comment by houjunchen** [comment]
PR #366 fixed this.
