### ISSUE TITLE
is_authenticated is bool and not callable

### ISSUE THREAD

**Issue by bagol** [mattupstate/flask-security#446]
Using [quick start](https://pythonhosted.org/Flask-Security/quickstart.html#basic-sqlalchemy-application) example with flask-security 1.7.4 (python-3.5), i have the following exception throwed:

    Traceback (most recent call last):
      File "/media/ext/virtualenvs/zero/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
        return self.wsgi_app(environ, start_response)
      File "/media/ext/virtualenvs/zero/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
        response = self.make_response(self.handle_exception(e))
      File "/media/ext/virtualenvs/zero/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "/media/ext/virtualenvs/zero/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
        raise value
      File "/media/ext/virtualenvs/zero/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
        response = self.full_dispatch_request()
      File "/media/ext/virtualenvs/zero/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/media/ext/virtualenvs/zero/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/media/ext/virtualenvs/zero/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
        raise value
      File "/media/ext/virtualenvs/zero/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
        rv = self.dispatch_request()
      File "/media/ext/virtualenvs/zero/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/media/ext/virtualenvs/zero/lib/python3.5/site-packages/flask_security/decorators.py", line 203, in wrapper
        if current_user.is_authenticated():
    TypeError: 'bool' object is not callable

I think that exact line should be written like this:

        if current_user.is_authenticated:

**Comment by yingbo** [comment]
Does your User class inherit class UserMixin? The example

```
class User(db.Model, UserMixin):
```

**Comment by aldarund** [comment]
https://github.com/mattupstate/flask-security/issues/416
but its not on pypi yet :((

**Comment by DotNetAge** [comment]
In Flask-login change logs  we can found this:


Version 0.3.0
-------------

Released on September 10th, 2015

...

- BREAKING: The `is_authenticated`, `is_active`, and `is_anonymous` members of
  the user class are now properties, not methods. Applications should update
  their user classes accordingly.

...


So all extensions use the `is_authenticated` as method will be break.

**Comment by DotNetAge** [comment]
The error is occurs in flask_security/decorators.py", line 203:

```python
def anonymous_user_required(f):
    @wraps(f)
    def wrapper(*args, **kwargs):
        if current_user.is_authenticated():
            return redirect(utils.get_url(_security.post_login_view))
        return f(*args, **kwargs)
    return wrapper
```

**Comment by jonafato** [comment]
Per @aldarund's link, this issue is fixed in the development branch, and the fix will be included in the next PyPI release.
