### ISSUE TITLE
Activate and Deactivate commands not working

### ISSUE THREAD

**Issue by edouardberthe** [mattupstate/flask-security#458]
The problem is :

```
(env)╭─edouard@macbook-pro-edouard  ~/test
╰─$ python manager.py activate -u berthe.ed@gmail.com
Config loaded with debug True
Traceback (most recent call last):
  File "manager.py", line 19, in <module>
    manager.run()
  File "/Users/edouard/Sites/remindmeal/env/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/Users/edouard/Sites/remindmeal/env/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/Users/edouard/Sites/remindmeal/env/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/Users/edouard/Sites/remindmeal/env/lib/python2.7/site-packages/flask_security/script.py", line 36, in wrapper
    fn(*args, **kwargs)
  File "/Users/edouard/Sites/remindmeal/env/lib/python2.7/site-packages/flask_security/script.py", line 131, in run
    _datastore.activate_user(user_identifier)
  File "/Users/edouard/Sites/remindmeal/env/lib/python2.7/site-packages/flask_security/datastore.py", line 146, in activate_user
    if not user.active:
AttributeError: 'str' object has no attribute 'active'
```

Because in the datastore, the command 'activate_user' take the identifier as argument and doesn't convert it into the entity User :

```
def activate_user(self, user):
        """Activates a specified user. Returns `True` if a change was made.

        :param user: The user to activate
        """
        if not user.active:
            user.active = True
            return True
        return False
```

I have made a fix : https://github.com/mattupstate/flask-security/pull/503

**Comment by jirikuncar** [comment]
Please use new CLI based on Click.
