### ISSUE TITLE
datetime objects used are not timezone aware

### ISSUE THREAD

**Issue by jadkik** [mattupstate/flask-security#466]
The `datetime.utcnow()` function is used anywhere the current datetime is needed. That function returns an offset-naive datetime object by design in [Python 2](https://docs.python.org/2/library/datetime.html#datetime.datetime.utcnow) and [Python 3](https://docs.python.org/3/library/datetime.html#datetime.datetime.utcnow).

This causes problems when using the `arrow` library for dates and times using e.g. SQLAlchemy with [`sqlalchemy_utils`](http://sqlalchemy-utils.readthedocs.org/en/latest/data_types.html#sqlalchemy_utils.types.arrow.ArrowType) installed.

Logging in after the first time fails because for some reason the dates are compared by sqlalchemy before committing the transaction, resulting in the following exception:

```
TypeError: can't compare offset-naive and offset-aware datetimes
```

If the datetime objects were timezone aware, there would not be a problem. And I think some database backends do store this information, so it might be better in those cases too. (I'm using MySQL, so it does not affect me in this regard)

**Comment by avilaton** [comment]
I hit the same issue. We are using postgresql and our tracking fields are created as `TIMESTAMP WITH TIME ZONE` and the user model uses `db.Column(db.DateTime(timezone=True))`. On the second login we get an error
```
Traceback (most recent call last):
  File "/home/gavila/.virtualenvs/st/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/gavila/.virtualenvs/st/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/gavila/.virtualenvs/st/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/home/gavila/.virtualenvs/st/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/gavila/.virtualenvs/st/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/gavila/.virtualenvs/st/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/gavila/.virtualenvs/st/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/home/gavila/.virtualenvs/st/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/gavila/.virtualenvs/st/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/gavila/.virtualenvs/st/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/gavila/.virtualenvs/st/lib/python2.7/site-packages/flask_security/decorators.py", line 225, in wrapper
    return f(*args, **kwargs)
  File "/home/gavila/.virtualenvs/st/lib/python2.7/site-packages/flask_security/views.py", line 76, in login
    login_user(form.user, remember=form.remember.data)
  File "/home/gavila/.virtualenvs/st/lib/python2.7/site-packages/flask_security/utils.py", line 82, in login_user
    identity=Identity(user.id))
  File "/home/gavila/.virtualenvs/st/lib/python2.7/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/home/gavila/.virtualenvs/st/lib/python2.7/site-packages/flask_principal.py", line 469, in _on_identity_changed
    self.set_identity(identity)
  File "/home/gavila/.virtualenvs/st/lib/python2.7/site-packages/flask_principal.py", line 418, in set_identity
    self._set_thread_identity(identity)
  File "/home/gavila/.virtualenvs/st/lib/python2.7/site-packages/flask_principal.py", line 463, in _set_thread_identity
    identity=identity)
  File "/home/gavila/.virtualenvs/st/lib/python2.7/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/home/gavila/.virtualenvs/st/lib/python2.7/site-packages/flask_security/core.py", line 215, in _on_identity_loaded
    for role in current_user.roles:
  File "/home/gavila/.virtualenvs/st/lib/python2.7/site-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/gavila/.virtualenvs/st/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 237, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/home/gavila/.virtualenvs/st/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 583, in get
    value = self.callable_(state, passive)
  File "/home/gavila/.virtualenvs/st/lib/python2.7/site-packages/sqlalchemy/orm/strategies.py", line 532, in _load_for_state
    return self._emit_lazyload(session, state, ident_key, passive)
  File "<string>", line 1, in <lambda>
    
  File "/home/gavila/.virtualenvs/st/lib/python2.7/site-packages/sqlalchemy/orm/strategies.py", line 602, in _emit_lazyload
    result = q.all()
  File "/home/gavila/.virtualenvs/st/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2584, in all
    return list(self)
  File "/home/gavila/.virtualenvs/st/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2731, in __iter__
    self.session._autoflush()
  File "/home/gavila/.virtualenvs/st/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1305, in _autoflush
    self.flush()
  File "/home/gavila/.virtualenvs/st/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2027, in flush
    self._flush(objects)
  File "/home/gavila/.virtualenvs/st/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2145, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/gavila/.virtualenvs/st/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/gavila/.virtualenvs/st/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2109, in _flush
    flush_context.execute()
  File "/home/gavila/.virtualenvs/st/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/home/gavila/.virtualenvs/st/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/home/gavila/.virtualenvs/st/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 170, in save_obj
    mapper, table, update)
  File "/home/gavila/.virtualenvs/st/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 632, in _emit_update_statements
    lambda rec: (
  File "/home/gavila/.virtualenvs/st/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 461, in _collect_update_commands
    value, state.committed_state[propkey]) is not True:
  File "/home/gavila/.virtualenvs/st/lib/python2.7/site-packages/sqlalchemy/sql/type_api.py", line 279, in compare_values
    return x == y
TypeError: can't compare offset-naive and offset-aware datetimes
```

**Comment by revmischa** [comment]
+1
