### ISSUE TITLE
'AnonymousUser' object has no attribute 'id'

### ISSUE THREAD

**Issue by bclark8923** [mattupstate/flask-security#467]
I'm trying to secure an endpoint with a token but whenever I submit a request with a bad token it blows up. Here's the callback.

I'm using the basic SQLAlchemy setup, any ideas of what causes this?

```
Traceback (most recent call last):
  File "/Users/mikaelastamas/Desktop/HDP/hdp-api/venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/mikaelastamas/Desktop/HDP/hdp-api/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/mikaelastamas/Desktop/HDP/hdp-api/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 270, in error_router
    return original_handler(e)
  File "/Users/mikaelastamas/Desktop/HDP/hdp-api/venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mikaelastamas/Desktop/HDP/hdp-api/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 267, in error_router
    return self.handle_error(e)
  File "/Users/mikaelastamas/Desktop/HDP/hdp-api/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mikaelastamas/Desktop/HDP/hdp-api/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mikaelastamas/Desktop/HDP/hdp-api/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 270, in error_router
    return original_handler(e)
  File "/Users/mikaelastamas/Desktop/HDP/hdp-api/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mikaelastamas/Desktop/HDP/hdp-api/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 267, in error_router
    return self.handle_error(e)
  File "/Users/mikaelastamas/Desktop/HDP/hdp-api/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mikaelastamas/Desktop/HDP/hdp-api/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/mikaelastamas/Desktop/HDP/hdp-api/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 471, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/mikaelastamas/Desktop/HDP/hdp-api/venv/lib/python2.7/site-packages/flask_security/decorators.py", line 117, in decorated
    if _check_token():
  File "/Users/mikaelastamas/Desktop/HDP/hdp-api/venv/lib/python2.7/site-packages/flask_security/decorators.py", line 63, in _check_token
    identity_changed.send(app, identity=Identity(user.id))
AttributeError: 'AnonymousUser' object has no attribute 'id'
```

**Comment by jonafato** [comment]
This shouldn't happen in normal use (i.e. `AnonymousUser` should not be authenticated, so the `if user and user.is_authenticated:` check on [this line](https://github.com/mattupstate/flask-security/blob/9583dc3e63af452eb3e23c919a4697554b168330/flask_security/decorators.py#L60) shouldn't evaluate to `True`). What versions of Flask-Security and Flask-Login are you using?

**Comment by bclark8923** [comment]
Flask-Login==0.3.2
Flask-Security==1.7.5

And it evaluated to true on that line, could I have gotten my system in a weird setup?

**Comment by bclark8923** [comment]
So I just wiped my virtualenv and reinstalled everything and it's working properly now, so I must have done something strange that got Flask-Security out of whack.

**Comment by jonafato** [comment]
@bclark8923 Great, glad it's working. I'll close this issue, then. Feel free to reopen it if the problem reappears.
