### ISSUE TITLE
sqlalchemy.exc.IntegrityError

### ISSUE THREAD

**Issue by tlaskyd** [mattupstate/flask-security#581]
# Register err
When I try to register the email that is already registered, `there is sqlalchemy.exc.IntegrityError`

**Comment by biomap** [comment]
You have a unique field on that column, which if that is the main user identifier is what you want.

**Comment by jirikuncar** [comment]
@tlaskyd can you confirm that you have `'email'` in `FLASK_USER_IDENTITY_ATTRIBUTES` configuration parameter?

**Comment by rabkins** [comment]
Hi,

I have this problem. When I try to register with same email I got `sqlalchemy.exc.IntegrityError`.
`FLASK_USER_IDENTITY_ATTRIBUTES` is set to `'emai'l` by default.

I extended RegisterForm and replaced email field with `EmailField` from `wtforms.fields.html5`

`email = EmailField('E-mail', validators=[email_required, email_validator])`

I used `email_required` and `email_validator` from `flask_security.forms`

**Comment by jirikuncar** [comment]
@rabkins can you please give us more information (full stacktrace,  `pip freeze`)?

**Comment by rabkins** [comment]
### pip freeze
alembic==0.9.2
amqp==2.1.4
Babel==2.4.0
billiard==3.5.0.2
blinker==1.4
celery==4.0.2
click==6.7
dominate==2.3.1
Flask==0.12.2
Flask-BabelEx==0.9.3
Flask-Bootstrap==3.3.7.1
Flask-DebugToolbar==0.10.1
Flask-Login==0.4.0
Flask-Mail==0.9.1
Flask-Migrate==2.0.4
Flask-Principal==0.4.0
Flask-Redis==0.3.0
Flask-Script==2.0.5
Flask-Security==3.0.0
Flask-SQLAlchemy==2.2
Flask-WTF==0.14.2
gunicorn==19.7.1
itsdangerous==0.24
Jinja2==2.9.6
kombu==4.0.2
Mako==1.0.6
MarkupSafe==1.0
nose==1.3.7
passlib==1.7.1
PyMySQL==0.7.11
python-dateutil==2.6.0
python-editor==1.0.3
pytz==2017.2
redis==2.10.5
six==1.10.0
speaklater==1.3
SQLAlchemy==1.1.10
vine==1.1.3
visitor==0.1.3
Werkzeug==0.12.2
WTForms==2.1

### stacktrace
```python
[2017-06-23 10:25:44][INFO][werkzeug._internal.py:_log:87][54bf0d8a-44c0-4273-812f-837507b91063] - 127.0.0.1 - - [23/Jun/2017 10:25:44] "POST /register HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/flask_security/decorators.py", line 230, in wrapper
    return f(*args, **kwargs)
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/flask_security/views.py", line 118, in register
    user = register_user(**form.to_dict())
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/flask_security/registerable.py", line 30, in register_user
    _datastore.commit()
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/flask_security/datastore.py", line 31, in commit
    self.db.session.commit()
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 906, in commit
    self.transaction.commit()
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 461, in commit
    self._prepare_impl()
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl
    self.session.flush()
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2171, in flush
    self._flush(objects)
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2291, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2255, in _flush
    flush_context.execute()
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 835, in _emit_insert_statements
    execute(statement, params)
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/pymysql/connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/pymysql/connections.py", line 1057, in _read_query_result
    result.read()
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/pymysql/connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/pymysql/connections.py", line 1014, in _read_packet
    packet.check_error()
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/Users/rabkins/.virtualenvs/my_proj/lib/python3.6/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.IntegrityError: (pymysql.err.IntegrityError) (1062, "Duplicate entry 'my@mail.com' for key 'email'") [SQL: 'INSERT INTO users (created_at, modified_at, email, password_hash, accept_tos, game_consent, marketing_consent, active, confirmed_at, last_login_at, current_login_at, last_login_ip, current_login_ip, login_count) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, %(email)s, %(password_hash)s, %(accept_tos)s, %(game_consent)s, %(marketing_consent)s, %(active)s, %(confirmed_at)s, %(last_login_at)s, %(current_login_at)s, %(last_login_ip)s, %(current_login_ip)s, %(login_count)s)'] [parameters: {'email': 'my@mail.com', 'password_hash': '$pbkdf2-sha512$25000$d04JoVQK4XwvBUAoh...', 'accept_tos': 1, 'game_consent': 1, 'marketing_consent': 1, 'active': 1, 'confirmed_at': None, 'last_login_at': None, 'current_login_at': None, 'last_login_ip': None, 'current_login_ip': None, 'login_count': None}]
```

### My extended RegisterForm

```python
from flask_security.forms import LoginForm, RegisterForm, Required,\
    email_required, email_validator
from wtforms import BooleanField
from wtforms.fields.html5 import EmailField


class MasterRegisterForm(RegisterForm):
    """Extended reg form."""

    email = EmailField('E-mail', [email_required, email_validator])


    accept_tos = BooleanField('TOS',
                              [Required(message='Required')])

    _game_consent = '''I agree ...
    '''
    game_consent = BooleanField('game cons',
                                [Required(message='Required')])

    _marketing_consent = '''I agree ...
    '''
    marketing_consent = BooleanField(_marketing_consent,
                                     [Required(message='Required')])
```

When I replaced in `flask_security/forms.py` `email = StringField(..)` to ` to `email = EmailField(...)` everything seems to work fine.
