### ISSUE TITLE
Unable to add role to user.

### ISSUE THREAD

**Issue by goelanshul** [mattupstate/flask-security#599]
I am trying to add role to user but get error always.
Here's the code for the same.

@app.before_first_request
def create_user():
    db.create_all()
    role_end_user = user_datastore.find_or_create_role(name='admin', description='Administrator')
    role_admin = user_datastore.find_or_create_role(name='end-user', description='End user')
    db.session.commit()
    password = utils.encrypt_password("test123")
user_datastore.create_user(email='t123@gmail.com', password=password,mobile_number="8611120316",roles= ['admin'])
    print user_datastore.add_role_to_user('t123@gmail.com','admin')
    db.session.commit()

Error I get all the time is : 

InvalidRequestError: Object '<User at 0x111866910>' is already attached to session '2' (this is '3')

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1607, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1654, in try_trigger_before_first_request_functions
    func()
  File "/Users/Anshul/PycharmProjects/ikinanki/server.py", line 33, in create_user
    print user_datastore.add_role_to_user('t123@gmail.com','admin')
  File "/usr/local/lib/python2.7/site-packages/flask_security/datastore.py", line 108, in add_role_to_user
    self.put(user)
  File "/usr/local/lib/python2.7/site-packages/flask_security/datastore.py", line 34, in put
    self.db.session.add(model)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1679, in add
    self._save_or_update_state(state)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1691, in _save_or_update_state
    self._save_or_update_impl(state)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1997, in _save_or_update_impl
    self._update_impl(state)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1980, in _update_impl
    to_attach = self._before_attach(state, obj)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2064, in _before_attach
    state.session_id, self.hash_key))

**Comment by italomaia** [comment]
Drop this line:

print user_datastore.add_role_to_user('t123@gmail.com','admin')

**Comment by goelanshul** [comment]
But, then how to add role to user.
I tried : 
user_datastore.add_role_to_user('t123@gmail.com','admin') 
as well and it gives the same error

**Comment by italomaia** [comment]
You mean here? 
user_datastore.create_user(email='t123@gmail.com', password=password,mobile_number="8611120316",roles= ['admin'])

You're adding the same role twice in your example.

**Comment by goelanshul** [comment]
That was just for testing combinations.
I've tried multiple combinations of the same.
Here's the list for that :
 `user_datastore.create_user(email='t123@gmail.com', password=password,mobile_number="8611120316",roles= ['admin'])
`
`user_datastore.add_role_to_user('t123@gmail.com','admin')`



But every time I commit my session post this, I get the following error : 
InvalidRequestError: Object '<User at 0x109299f50>' is already attached to session '2' (this is '3')

**Comment by jirikuncar** [comment]
Is it possible that you are executing the `create_user` function twice (e.g. multiple threads)? 

Also use `datastore.commit()` instead of `db.session.commit()`.
