### ISSUE TITLE
How to use Basic HTTP authentication?

### ISSUE THREAD

**Issue by ghostku** [mattupstate/flask-security#605]
I'm trying to use Basic HTTP auth. So I just took QuickStart Manual from (here)[https://pythonhosted.org/Flask-Security/quickstart.html#id1] and change view decorator from `@login_required` to `@http_auth_required` but it says

> Traceback (most recent call last):
> 
>   File "C:\Python\lib\site-packages\flask\app.py", line 1994, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\Python\lib\site-packages\flask\app.py", line 1985, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\Python\lib\site-packages\flask\app.py", line 1540, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Python\lib\site-packages\flask\_compat.py", line 33, in reraise
>     raise value
>   File "C:\Python\lib\site-packages\flask\app.py", line 1982, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\Python\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Python\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Python\lib\site-packages\flask\_compat.py", line 33, in reraise
>     raise value
>   File "C:\Python\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Python\lib\site-packages\flask\app.py", line 1598, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "C:\Python\lib\site-packages\flask_security\decorators.py", line 92, in wrapper
>     if _check_http_auth():
>   File "C:\Python\lib\site-packages\flask_security\decorators.py", line 73, in _check_http_auth
>     if user and utils.verify_and_update_password(auth.password, user):
>   File "C:\Python\lib\site-packages\flask_security\utils.py", line 134, in verify_and_update_password
>     if _pwd_context.identify(user.password) != 'plaintext':
>   File "C:\Python\lib\site-packages\passlib\context.py", line 2188, in identify
>     record = self._identify_record(hash, category, required)
>   File "C:\Python\lib\site-packages\passlib\context.py", line 1121, in identify_record
>     raise ExpectedStringError(hash, "hash")
> TypeError: hash must be unicode or bytes, not None

Where did I make a mistake&

**Comment by stamaimer** [comment]
@ghostku Have you ever solve the problem?

**Comment by kalkehcoisa** [comment]
The problem started happening here too.

**Comment by jirikuncar** [comment]
Is it possible that you have a user with an empty password?

**Comment by kalkehcoisa** [comment]
Sorry for taking long. Was working on other issues.
Yes, it is very likely that the user had an empty password.
Checked the database and found some users that still have the password field empty.
Perhaps making the default to password to blank solves the problem?

**Comment by jirikuncar** [comment]
I would like to understand, how you created user with password equal to `None`, so we can avoid this problem in the future.

**Comment by kalkehcoisa** [comment]
I think the users, including my own, were created using python-social-auth.
Once it uses the simplest way of logging in. It doesn't ask for a password any time.

**Comment by jirikuncar** [comment]
I see several problems (validation, security) with using change password handler when an initial password has not been set. I would propose using `/reset` handler for creating initial password. We can add redirect from `/change` if `user.password` is `None`.

**Comment by kalkehcoisa** [comment]
I'm going to try that.
For now, as I fast fix. I'm setting up the initial value to the password in the database as a random uuid and some system variables. So, they can't login using that password, they have to create a proper one later and it avoid the problem with flask-security.
