### ISSUE TITLE
Flask Mongo Engine Creating User

### ISSUE THREAD

**Issue by drcrook1** [mattupstate/flask-security#667]
The backend is Azure's Cosmos DB using the Mongo API.  Not 100% sure if this is a Cosmos DB issue or a Flask Security Issue.

Flask-Security version==1.7.5

ERROR:
mongoengine.errors.FieldDoesNotExist
mongoengine.errors.FieldDoesNotExist: The fields "{'_t', 'errmsg', '$err', 'ok', 'code'}" do not exist on the document "User"

Traceback (most recent call last)
File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
response = self.handle_exception(e)
File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
raise value
File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
raise value
File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python3.5/dist-packages/flask_security/decorators.py", line 225, in wrapper
return f(*args, **kwargs)
File "/usr/local/lib/python3.5/dist-packages/flask_security/views.py", line 75, in login
if form.validate_on_submit():
File "/usr/local/lib/python3.5/dist-packages/flask_wtf/form.py", line 101, in validate_on_submit
return self.is_submitted() and self.validate()
File "/usr/local/lib/python3.5/dist-packages/flask_security/forms.py", line 230, in validate
self.user = _datastore.get_user(self.email.data)
File "/usr/local/lib/python3.5/dist-packages/flask_security/datastore.py", line 226, in get_user
rv = self.user_model.objects(**query).first()
File "/usr/local/lib/python3.5/dist-packages/mongoengine/queryset/base.py", line 300, in first
result = queryset[0]
File "/usr/local/lib/python3.5/dist-packages/mongoengine/queryset/base.py", line 200, in __getitem__
only_fields=self.only_fields
File "/usr/local/lib/python3.5/dist-packages/mongoengine/base/document.py", line 730, in _from_son
obj = cls(__auto_convert=False, _created=created, __only_fields=only_fields, **data)
File "/usr/local/lib/python3.5/dist-packages/mongoengine/base/document.py", line 78, in __init__
raise FieldDoesNotExist(msg)
mongoengine.errors.FieldDoesNotExist: The fields "{'_t', 'errmsg', '$err', 'ok', 'code'}" do not exist on the document "User"

**Comment by jirikuncar** [comment]
Can you check if you get the same error with `Flask-Security==3.0.0`?

Out of curiosity can you tell me what is in variable `query` in:
```
File "/usr/local/lib/python3.5/dist-packages/flask_security/datastore.py", line 226, in get_user
rv = self.user_model.objects(**query).first()
```

**Comment by spirosoik** [comment]
@jirikuncar the query has `email_iexact` which seems that doesn't work not even for login.

**Comment by jirikuncar** [comment]
@spirosoik that is strange. It means that the tests are not checking everything on MongoDB. Would you have a time to submit a PR?
