### ISSUE TITLE
RecursionError: maximum recursion depth exceeded in comparison

### ISSUE THREAD

**Issue by velerodro** [mattupstate/flask-security#718]
Hello,

The way I create the flask app is the following. I have:
```
/manage.py
/appl/__init.py__
```

Where `manage.py` contains:
```
  from appl import manager
  manager.run()
```

And `__init__.py` contains:
```
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_script import Manager
from flask_migrate import Migrate, MigrateCommand
from flask_security import Security, SQLAlchemyUserDatastore

app = Flask(__name__, static_url_path = "")
app.config.from_pyfile('config.py')

db = SQLAlchemy(app)
migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)

# for some reason this lines have to be in here
from appl import views, models

# Setup Flask-Security
user_datastore = SQLAlchemyUserDatastore(db, models.User, models.Role)
security = Security(app, user_datastore)
```

With this configuration, whenever I try to visit `/register` I get:
`RecursionError: maximum recursion depth exceeded in comparison`
(I put the traceback at the end)

I am using python 3.6. I used to use this same approach in the past with python2.7 and former flask-security versions and worked without errors. 

Any ideas about how could I solve this issue?

Thanks!

```
127.0.0.1 - - [21/Oct/2017 17:08:23] "GET /register HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/flask_security/decorators.py", line 230, in wrapper
    return f(*args, **kwargs)
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/flask_security/views.py", line 139, in register
    **_ctx('register'))
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/flask_security/core.py", line 528, in render_template
    return render_template(*args, **kwargs)
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/flask_security/templates/security/register_user.html", line 6, in top-level template code
    {{ render_field_with_errors(register_user_form.email) }}
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/jinja2/runtime.py", line 553, in _invoke
    rv = self._func(*arguments)
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/flask_security/templates/security/_macros.html", line 3, in template
    {{ field.label }} {{ field(**kwargs)|safe }}
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/wtforms/fields/core.py", line 390, in __html__
    return self()
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/wtforms/fields/core.py", line 399, in __call__
    return widgets.HTMLString('<label %s>%s</label>' % (attributes, text or self.text))
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/speaklater.py", line 133, in __str__
    return str(self.value)
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__
    return getattr(self.value, name)
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/speaklater.py", line 177, in __getattr__

......... goes on like this for a bunch of lines more

 File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/speaklater.py", line 115, in <lambda>
    value = property(lambda x: x._func(*x._args, **x._kwargs))
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/werkzeug/local.py", line 375, in <lambda>
    __call__ = lambda x, *a, **kw: x._get_current_object()(*a, **kw)
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/flask_security/utils.py", line 47, in <lambda>
    localize_callback = LocalProxy(lambda: _security.i18n_domain.gettext)
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/flask_security/utils.py", line 39, in <lambda>
    _security = LocalProxy(lambda: current_app.extensions['security'])
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/flask/globals.py", line 49, in _find_app
    top = _app_ctx_stack.top
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/werkzeug/local.py", line 166, in top
    return self._local.stack[-1]
  File "/Users/u/3virtualenvs/project/lib/python3.6/site-packages/werkzeug/local.py", line 70, in __getattr__
    return self.__storage__[self.__ident_func__()][name]
RecursionError: maximum recursion depth exceeded in comparison
```

**Comment by velerodro** [comment]
I tracked it down to this commit: https://github.com/mattupstate/flask-security/commit/c027cea33af1df567233eaa83967791cae8e7350

Until that one it works fine. When I update to that commit, then I start getting the error above.

**Comment by velerodro** [comment]
Apparently, related to #715 , the issue was being caused because I use flask-babel in the project. I removed flask-babel and now it is working.

**Comment by aarti-b** [comment]
please add:
import sys
sys.setrecursionlimit(some_number)
you will be done!
