### ISSUE TITLE
Error sending email

### ISSUE THREAD

**Issue by lormayna** [mattupstate/flask-security#738]
Hi, I'm trying to use flask-security to authenticate users.
Everything seems working fine except the email sending. 
This is the traceback of the error:

`Traceback (most recent call last):
  File "/home/lorenzo/project/security/lib/python3.5/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/lorenzo/project/security/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/lorenzo/project/security/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lorenzo/project/security/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/lorenzo/project/security/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lorenzo/project/security/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lorenzo/project/security/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lorenzo/project/security/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/lorenzo/project/security/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lorenzo/project/security/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lorenzo/project/security/lib/python3.5/site-packages/flask_security/views.py", line 198, in send_confirmation
    send_confirmation_instructions(form.user)
  File "/home/lorenzo/project/security/lib/python3.5/site-packages/flask_security/confirmable.py", line 44, in send_confirmation_instructions
    confirmation_link=confirmation_link)
  File "/home/lorenzo/project/security/lib/python3.5/site-packages/flask_security/utils.py", line 401, in send_mail
    mail.send(msg)
  File "/home/lorenzo/project/security/lib/python3.5/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/home/lorenzo/project/security/lib/python3.5/site-packages/flask_mail.py", line 427, in send
    connection.send(self)
  File "/home/lorenzo/project/security/lib/python3.5/site-packages/flask_mail.py", line 188, in send
    self.host.sendmail(sanitize_address(envelope_from or message.sender),
  File "/home/lorenzo/project/security/lib/python3.5/site-packages/flask_mail.py", line 105, in sanitize_address
    nm, addr = addr
ValueError: too many values to unpack (expected 2)
`

I have installed everything with pip.

Let me know if you need more informations.

**Comment by pyxze** [comment]
Try running this command:

`pip install --upgrade git+
https://github.com/mattupstate/flask-security.git@develop`

You can read the details here:

https://github.com/mattupstate/flask-security/pull/695#issuecomment-338435733

**Comment by lormayna** [comment]
I tried it and it seems solve the problem.
When this will be pushed on the stable branch?


Il 31 dic 2017 8:05 AM, "pyxze" <notifications@github.com> ha scritto:

**Comment by NoHeDidnt** [comment]
I get the same error and running the command raises a 406-Error.

**Comment by johnclaro** [comment]
Hi @NoHeDidnt,

This issue helped me out https://github.com/mattupstate/flask-security/issues/685. Setting a value for SECURITY_EMAIL_SENDER fixed the problem for me.

**Comment by spitzbubchen** [comment]
pip install --upgrade git+git://github.com/mattupstate/flask-security.git@develop worked for me
