### ISSUE TITLE
Email Confirmation raises sqlalchemy.exc.InvalidRequestError

### ISSUE THREAD

**Issue by apmechev** [mattupstate/flask-security#795]
Hi all, 

I'm attempting to use the ConfirmRegisterForm in flask-security, however when the confirmation email is clicked, I get an sqlalchemy.exc.InvalidRequestError

views.py:
~~~~
from flask import render_template, flash, redirect, request, session
from my_app.database import db_session, init_db
from my_app import app

from flask_security import Security, UserMixin, RoleMixin, login_required, SQLAlchemySessionUserDatastore
from .forms import LoginForm
from flask_oauth import OAuth
from my_app import models
from my_app.models import User, Role
from flask_security.forms import RegisterForm
from flask_security.forms import ConfirmRegisterForm, Required, StringField

from my_app import db

user_datastore = SQLAlchemySessionUserDatastore(db_session,
                                                User, Role)

class ExtendedConfirmRegisterForm(ConfirmRegisterForm):
    username = StringField('Username', [Required()])

security = Security(app, user_datastore , confirm_register_form=ExtendedConfirmRegisterForm)

@app.teardown_appcontext
def shutdown_session(exception=None):
    db_session.remove()
~~~~

\_\_init\_\_.py
~~~~
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_migrate import Migrate

app = Flask(__name__)
app.config.from_pyfile('config.py')
db = SQLAlchemy(app)
migrate = Migrate(app, db)

Model = db.Model
from my_app import views, models
~~~~

model.py
~~~~
from my_app.database import Base
from my_app import Model
from flask_security import UserMixin, RoleMixin
from sqlalchemy import create_engine
from sqlalchemy.orm import relationship, backref
from sqlalchemy import Boolean, DateTime, Column, Integer, String, ForeignKey, Float
from flask_migrate import Migrate

class User(Model, UserMixin):
 ....
~~~~

database.py
~~~~
from sqlalchemy import create_engine
from sqlalchemy.orm import scoped_session, sessionmaker
from sqlalchemy.ext.declarative import declarative_base
from my_app.config import SQLALCHEMY_DATABASE_URI

engine = create_engine(SQLALCHEMY_DATABASE_URI, \
                       convert_unicode=True)

db_session = scoped_session(sessionmaker(autocommit=True,
                                         autoflush=False,
                                         bind=engine))
Base = declarative_base()
Base.query = db_session.query_property()
~~~~

I would guess there's an issue with the order of imports, since the rest of my code is taken from the flask and flask-security tutorials, and I'm just using the regular ConfirmRegisterForm with an extra field. 

here is the backtrace I get when I click on the confirmation email:

~~~~
ERROR in app: Exception on /confirm/WyIxMyIsIiQ1JHJvdW5kcz01MzUwMDAkakp0dElmUXBhWkZ2RDJ4MCRvNVlleWQ5cmJYMUJKUTdtM1J0VE9Vd1dJR3JpdW9sSGpUSFZWMzV2ZWo1Il0.DkOGCQ.sgV8Z0T5AAVNn85VBS8rby0qnyU [GET]
Traceback (most recent call last):
  File "/home/apmechev/apmechev_files/my_app/flask/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/apmechev/apmechev_files/my_app/flask/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
  rv = self.handle_user_exception(e)
File "/home/apmechev/apmechev_files/my_app/flask/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
  reraise(exc_type, exc_value, tb)
File "/home/apmechev/apmechev_files/my_app/flask/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
  raise value
File "/home/apmechev/apmechev_files/my_app/flask/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
  rv = self.dispatch_request()
File "/home/apmechev/apmechev_files/my_app/flask/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
  return self.view_functions[rule.endpoint](**req.view_args)
File "/home/apmechev/apmechev_files/my_app/flask/lib/python3.5/site-packages/flask_security/views.py", line 236, in confirm_email
  if confirm_user(user):
File "/home/apmechev/apmechev_files/my_app/flask/lib/python3.5/site-packages/flask_security/confirmable.py", line 90, in confirm_user
  _datastore.put(user)
File "/home/apmechev/apmechev_files/my_app/flask/lib/python3.5/site-packages/flask_security/datastore.py", line 34, in put
  self.db.session.add(model)
File "/home/apmechev/apmechev_files/my_app/flask/lib/python3.5/site-packages/sqlalchemy/orm/scoping.py", line 153, in do 
  return getattr(self.registry(), name)(*args, **kwargs)
File "/home/apmechev/apmechev_files/my_app/flask/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 1776, in add
  self._save_or_update_state(state)
File "/home/apmechev/apmechev_files/my_app/flask/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 1789, in _save_or_update_state
  self._save_or_update_impl(state)
File "/home/apmechev/apmechev_files/my_app/flask/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2106, in _save_or_update_impl
  self._update_impl(state)
File "/home/apmechev/apmechev_files/my_app/flask/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2089, in _update_impl
  to_attach = self._before_attach(state, obj)
File "/home/apmechev/apmechev_files/my_app/flask/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2179, in 
 _before_attach
    state.session_id, self.hash_key))
sqlalchemy.exc.InvalidRequestError: Object '<User at 0x7f3ed4d7f908>' is already attached to session '1' (this is '2')
~~~~

Thanks in advance!

**Comment by apmechev** [comment]
Repeatedly visiting the link also increments the session number: 

~~~
sqlalchemy.exc.InvalidRequestError: Object '<User at 0x7f976e71a048>' is already attached to session '7' (this is '8'); 
~~~
Am I missing a 'commit' somewhere?

**Comment by apmechev** [comment]
Solved by not using the SQLAlchemyUserSessionDatastore but the SQLAlchemyUserDatastore:

~~~~
-from flask_security import Security, UserMixin, RoleMixin, login_required, SQLAlchemySessionUserDatastore
+from flask_security import Security, UserMixin, RoleMixin, login_required, SQLAlchemySessionUserDatastore, SQLAlchemyUserDatastore


-user_datastore = SQLAlchemySessionUserDatastore(db_session,
+user_datastore = SQLAlchemyUserDatastore(db,
                                                 User, Role)
 
 @app.teardown_appcontext
 def shutdown_session(exception=None):
-    db_session.remove()
+    db.session.remove()
 ~~~~
