### ISSUE TITLE
Can't get Forgot Password functionality to work

### ISSUE THREAD

**Issue by ekw** [mattupstate/flask-security#92]
I'm trying to use the default Forgot Password functionality in Flask-Security module. On the Forgot Password view, I enter my email address, click Recover Password and successfully received the reset password email. When I click the link in the email, I go to the Reset Password view as expected. When I try to enter a new password and submit, however, I get this stack trace:

```
Traceback (most recent call last):
File "/opt/virtualenvs/project/local/lib/python2.7/site-packages/flask/app.py", line 1701, in __call__
  return self.wsgi_app(environ, start_response)
File "/opt/virtualenvs/project/local/lib/python2.7/site-packages/flask/app.py", line 1689, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/opt/virtualenvs/project/local/lib/python2.7/site-packages/flask/app.py", line 1687, in wsgi_app
  response = self.full_dispatch_request()
File "/opt/virtualenvs/project/local/lib/python2.7/site-packages/flask/app.py", line 1360, in full_dispatch_request
  rv = self.handle_user_exception(e)
File "/opt/virtualenvs/project/local/lib/python2.7/site-packages/flask/app.py", line 1358, in full_dispatch_request
  rv = self.dispatch_request()
File "/opt/virtualenvs/project/local/lib/python2.7/site-packages/flask/app.py", line 1344, in dispatch_request
  return self.view_functions[rule.endpoint](**req.view_args)
File "/opt/virtualenvs/project/local/lib/python2.7/site-packages/flask_security/decorators.py", line 171, in wrapper
  return f(*args, **kwargs)
File "/opt/virtualenvs/project/local/lib/python2.7/site-packages/flask_security/views.py", line 264, in reset_password
  update_password(user, form.password.data)
File "/opt/virtualenvs/project/local/lib/python2.7/site-packages/flask_security/recoverable.py", line 78, in update_password
  _datastore.put(user)
File "/opt/virtualenvs/project/local/lib/python2.7/site-packages/flask_security/datastore.py", line 31, in put
  self.db.session.add(model)
File "/opt/virtualenvs/project/local/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 149, in do
  return getattr(self.registry(), name)(*args, **kwargs)
File "/opt/virtualenvs/project/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1371, in add
  self._save_or_update_state(state)
File "/opt/virtualenvs/project/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1383, in _save_or_update_state
  self._save_or_update_impl(state)
File "/opt/virtualenvs/project/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1639, in _save_or_update_impl
  self._update_impl(state)
File "/opt/virtualenvs/project/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1633, in _update_impl
  self._attach(state)
File "/opt/virtualenvs/project/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1721, in _attach
  state.session_id, self.hash_key))
sqlalchemy.exc.InvalidRequestError: Object '<User at 0xa362a4c>' is already attached to session '33' (this is '34')
```

Can anyone help me with this?  I'm using: Flask==0.9, Flask-SQLAlchemy==0.16, Flask-Security==1.5.4

**Comment by agua19940824** [comment]
I have same problem.
Flask-Security ==1.7.5
Flask-SQLAlchemy==2.2
SQLAlchemy==1.1.9
```
main.py
from flask_sqlalchemy import SQLAlchemy
from flask_security import current_user, login_required, RoleMixin, Security, \
	SQLAlchemyUserDatastore, UserMixin, utils
app = Flask(__name__)
app.config.from_object('config')
db = SQLAlchemy(app)
```
```
config.py

#SQLALCHEMY_COMMIT_ON_TEARDOWN = True
```
When I didn't  set SQLALCHEMY_COMMIT_ON_TEARDOWN = True,  after submit the reset_password_form, it appears **sqlalchemy.orm.exc.DetachedInstanceError: Parent instance <User at 0x6d415c0> is not bound to a Session; lazy load operation of attribute 'roles' cannot proceed** and the new password didn't put into the database.

When I set SQLALCHEMY_COMMIT_ON_TEARDOWN = True, click RecoverPassword button , it appears **sqlalchemy.orm.exc.DetachedInstanceError: Instance <User at 0x6af0320> is not bound to a Session; attribute refresh operation cannot proceed**, but i can through the email link change my password..
